@startuml Order Update
' actor User as "SalesRep / Inventory Manager"
' participant "OrderController" as Controller
participant "OrderService" as ServiceInterface
' participant "OrderUpdateStrategy" as StrategyInterface
' participant "PendingOrderUpdateStrategy" as PendingStrategy
' participant "ProcessedOrderUpdateStrategy" as ProcessedStrategy
' participant "DeliveredOrderUpdateStrategy" as DeliveredStrategy
participant "Order" as OrderEntity
participant "OrderRepository" as Repo
participant "OrderStatusObserver" as ObserverInterface
participant "CustomerDeliveryStatusObserver" as DeliveryObserver
participant "NotificationService" as NotificationInterface
participant "EmailNotificationService" as Notification
participant "OrderCheckScheduler" as Scheduler
participant "StaffPendingOrderNotificationObserver" as PendingObserver

' User -> Controller : updateOrder(orderId, orderDto)
' Controller -> ServiceInterface : updateOrder(orderId, orderDto)
' ServiceInterface -> OrderEntity : getOrderStatus()
' OrderEntity --> ServiceInterface : currentState

' alt if state is Pending
'     ServiceInterface -> StrategyInterface : getStrategy(currentState)
'     StrategyInterface -> PendingStrategy : updateOrder(order, orderDto)
'     PendingStrategy -> Repo : save(order)
' else if state is Processed
'     ServiceInterface -> StrategyInterface : getStrategy(currentState)
'     StrategyInterface -> ProcessedStrategy : updateOrder(order, orderDto)
'     ProcessedStrategy -> Repo : save(order)
' else if state is Delivered
'     ServiceInterface -> StrategyInterface : getStrategy(currentState)
'     StrategyInterface -> DeliveredStrategy : updateOrder(order, orderDto)
' end

Repo --> ServiceInterface : orderSaved
ServiceInterface -> OrderEntity : getOrderStatus()
OrderEntity --> ServiceInterface : currentState

alt if order status is Delivered
    ServiceInterface -> ObserverInterface : notifyObservers(order)
    ObserverInterface -> DeliveryObserver : notify(order)
    DeliveryObserver -> NotificationInterface : sendNotification(customerConntact, subject, message)
    NotificationInterface -> Notification : sendNotification(customerConntact, subject, message)
end

== Scheduled Order Checks ==

Scheduler -> Repo : findPendingOrdersOlderThanDays(2)
Repo --> Scheduler : pendingOrders
Scheduler -> ObserverInterface : notifyObservers(pendingOrders)
ObserverInterface -> PendingObserver : notify(pendingOrders)
PendingObserver -> NotificationInterface : sendNotification(salesRepContact,subject, message)
NotificationInterface -> Notification : sendNotification(salesRepContact, subject, message)


@enduml
