FROM maven:3.8-openjdk-17

# install watch
RUN microdnf install procps-ng ; microdnf clean all

RUN mkdir /be
WORKDIR /be

ADD ./bin/docker-entrypoint.dev.sh ./

RUN sed -i -e 's/\r$//' ./bin/docker-entrypoint.dev.sh

