name: BackEnd Java Project

on:
  push:
    paths:
      - backend/**
      - .github/workflows/**

jobs:
  gjf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        run: mvn --batch-mode --update-snapshots verify

  # TODO: AWS
  # deploy:
  #   if: success() && github.ref_name == 'main'
  #   runs-on: ubuntu-latest
  #   needs: ci

